name: 'Streamlit App Action'
description: 'Validate a Streamlit app with smoke tests and linting'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  app-path:
    description: 'Filepath to the main app file (`streamlit run <this>`)'
    required: false
    default: 'streamlit_app.py'
  ruff:
    description: 'Run ruff linting'
    required: false
    default: 'false'
  pytest-args:
    description: 'Command line arguments to pass to pytest'
    required: false
    default: '-v'
  skip-smoke:
    description: 'Skip the provided smoke test. Useful if your app testing requires advanced setup.'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      # Note: This is basically a no-op if you don't use `requirements.txt`.
      # In that case, add a step in your workflow to install dependencies
      # using your own package manager before calling streamlit-app-action.
      shell: bash
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - if: ${{ inputs.ruff == 'true' }}
      name: Lint with ruff
      uses: chartboost/ruff-action@v1
      # TODO: Add ability to define example secrets.toml values for smoke test
    - name: Test with pytest
      shell: bash
      run: |
        cd src
        cp $GITHUB_ACTION_PATH/*.py .
        
        python -m pytest ${{ inputs.pytest-args }}
      env:
        APP_PATH: ${{ inputs.app-path }}
        SKIP_SMOKE: ${{ inputs.skip-smoke }}
